[package]
name = "ci-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
redis = { version = "0.29.0", features = ["tokio-rustls-comp"] }
tokio = { version = "1.43.0", features = ["full"] }
