name: 'publish apk'

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        with:
          name: yadokani389

      - name: Build
        run: nix develop -i -c bash -c "pnpm i && cargo tauri android build"

      - name: Get app version
        run: echo "APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
