name: 'test'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: Test
        run: |
          nix run .#dev -- -D
          nix develop -c cargo test
          nix develop -c process-compose down

      - name: Clippy
        run: nix develop -c cargo clippy -- -Dwarnings
