name: 'test'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: use flake
        run: echo "use flake" > .envrc

      - uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - name: fastfetch
        run: fastfetch

      - name: Test
        run: |
          nix run .#dev -- -D
          cargo test
          process-compose down

      - name: Clippy
        run: cargo clippy -- -Dwarnings
