name: 'test'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: use flake
        run: echo "use flake" > .envrc

      - uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - run: mkdir -p data/r1

      - run: nix run .#dev -- -D -L log

      - run: sleep 10

      - run: cat log

      - run: cargo make run
